version: "3.9"
services:
  database:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - "pw_database:/var/lib/postgresql/data"
    env_file:
      - .env
  # backend:
  #   build: ./
  #   container_name: backend
  #   ports:
  #     - "3000:3000"

volumes:
  pw_database:
