version: "3.9"
services:
  database:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - "database:/var/lib/postgresql/data"
    env_file:
      - .env
volumes:
  database:
