version: "3.9"
services:
  database:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - "database:/var/lib/postgresql/data"
    env_file:
      - .env
  backend:
    build: ./
    hostname: backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - database

volumes:
  database:
